// app/src/lib/components/layout/Footer.svelte
<script lang="ts">
	import SocialLinks from '../shared/SocialLinks.svelte';
	import EmailSubscribe from '$lib/components/shared/EmailSubscribe.svelte';
	import logoLeaf from '$lib/assets/logo-leaf.png';
</script>

<footer class="bg-surface-light-alt dark:bg-surface-dark-alt">
	<div class="mx-auto max-w-6xl px-6 py-12">
		<!-- Top section: Logo -->
		<div class="flex justify-center">
			<!-- Logo -->
			<a href="/" class="flex gap-5 items-center">
				<img src={logoLeaf} alt="Growing Me logo" class="h-10 w-10 rounded-full" />
				<span class="font-heading text-xl font-semibold text-gray-900 dark:text-gray-100"
					>Growing Me</span
				>
			</a>
		</div>

		<!-- Green divider -->
		<div class="mx-auto flex max-w-6xl px-6 my-4 h-[2px] bg-brand"></div>

		<!-- Nav links -->
		<div class="flex justify-center py-2">
			<nav>
				<ul class="flex items-center gap-4">
					<li>
						<a
							href="/"
							class="text-sm text-gray-600 transition-colors hover:text-brand dark:text-gray-400 dark:hover:text-sage-300"
							>Home</a
						>
					</li>
					<li>
						<a
							href="/about"
							class="text-sm text-gray-600 transition-colors hover:text-brand dark:text-gray-400 dark:hover:text-sage-300"
							>About</a
						>
					</li>
					<li>
						<a
							href="/articles"
							class="text-sm text-gray-600 transition-colors hover:text-brand dark:text-gray-400 dark:hover:text-sage-300"
							>Articles</a
						>
					</li>
					<li>
						<a
							href="/podcast"
							class="text-sm text-gray-600 transition-colors hover:text-brand dark:text-gray-400 dark:hover:text-sage-300"
							>Podcast</a
						>
					</li>
					<li>
						<a
							href="/contact"
							class="text-sm text-gray-600 transition-colors hover:text-brand dark:text-gray-400 dark:hover:text-sage-300"
							>Contact</a
						>
					</li>
				</ul>
			</nav>
		</div>

		<!-- Subscribe section -->
		<div class="flex justify-center pt-8">
			<EmailSubscribe />
		</div>

		<!-- Bottom: Social + Copyright -->
		<div
			class="mt-8 flex flex-col items-center gap-4 pt-4 dark:border-sage-700"
		>
			<SocialLinks size={18} />
			<p class="text-xs text-gray-500 dark:text-gray-500 py-3">
				&copy; {new Date().getFullYear()} Growing Me. All rights reserved.
			</p>
		</div>
	</div>
</footer>

// web/src/ui/Footer.tsx
import { Icon } from '@iconify/react';
import Link from 'next/link';
import Image from 'next/image';

export default function Footer() {
  return (
    <footer className="navbar flex-col bg-base-100 w-full justify-center">
		<div className="flex">
			<div className="">
				<Image src="/public/leaf.png" alt="leaf" width={8} height={8} />
			</div>
			<div>
				<p>Growing Me</p>
			</div>
		</div>

		<div className="flex w-full border-1 border-[#186733]" />

		<div className="items-center">
			<ul className="menu menu-horizontal list-none">
				<li>
					<Link href="/" className="text-xl">
						Home
					</Link>
				</li>
				<li>
					<Link href="/about" className="text-xl">
						About
					</Link>
				</li>
				<li>
					<Link href="/articles" className="text-xl">
						Articles
					</Link>
				</li>
				<li>
					<Link href="/gallery" className="text-xl">
						Gallery
					</Link>
				</li>
			</ul>
		</div>
		
		<form className="">
			<fieldset className="form-control flex w-80">
				<div className="join">
					<input
					type="text"
					placeholder="Enter email..."
					className="input input-bordered join-item" />
					<button className="btn btn-primary join-item">Subscribe</button>
				</div>
				<Image src="/public/leaf.png" alt="leaf" width={8} height={8} />
			</fieldset>
		</form>

		<div className="">
			<ul className="menu menu-horizontal list-none">
				<li>
					<a href="#" className="w-8 h-8">
						<Icon icon="fa6-brands:square-bluesky" />
					</a>
				</li>
				<li>
					<a href="#" className="w-8 h-8">
						<Icon icon="fa6-brands:tiktok" />
					</a>
				</li>
				<li>
					<a href="#" className="w-10 h-10">
						<Icon icon="fa6-brands:discord" />
					</a>
				</li>
			</ul>
		</div>
		<p className="">Copyright © {new Date().getFullYear()} - All rights reserved</p>
	</footer>
  )
}
