// expo-app/shared/components/Footer.tsx
import { View, Text } from "react-native";
import { Link } from "expo-router";
import { Image } from "expo-image";

export default function Footer() {
  return (
    <View className="w-full bg-gray-800 py-8">
      <View className="max-w-7xl mx-auto px-6">
        <View className="flex-row justify-between items-start">
          <View className="flex-1 mr-12">
            <View className="h-10 w-52 mb-4">
              <Image
                source={require("@/assets/images/logo.png")}
                className="w-full h-full object-contain"
                contentFit="contain"
              />
            </View>
            <Text className="text-gray-300">
              Description / Tag Line
            </Text>
          </View>

          <View className="flex-1">
            <Text className="text-white font-bold mb-4">Quick Links</Text>
            <Link href="/about" className="text-gray-300 mb-2">About</Link>
            <Link href="/articles" className="text-gray-300 mb-2">Articles</Link>
            <Link href="/podcasts" className="text-gray-300">Podcasts</Link>
          </View>

          <View className="flex-1">
            <Text className="text-white font-bold mb-4">Contact</Text>
            <Text className="text-gray-300 mb-2">Email: contact@example.com</Text>
            <Text className="text-gray-300">Phone: (555) 123-4567</Text>
          </View>
        </View>

        <View className="mt-8 pt-8 border-t border-gray-700">
          <Text className="text-gray-400 text-center">
            © {new Date().getFullYear()} Valkyrie Remedy LLC. All rights reserved.
          </Text>
        </View>
      </View>
    </View>
  );
}

// app/src/lib/components/layout/Footer.svelte
<script lang="ts">
	import SocialLinks from '../shared/SocialLinks.svelte';
	import EmailSubscribe from '$lib/components/shared/EmailSubscribe.svelte';
	import logoLeaf from '$lib/assets/logo-leaf.png';
</script>

<footer class="bg-surface-light-alt dark:bg-surface-dark-alt">
	<div class="mx-auto max-w-6xl px-6 py-12">
		<!-- Top section: Logo -->
		<div class="flex justify-center">
			<!-- Logo -->
			<a href="/" class="flex gap-5 items-center">
				<img src={logoLeaf} alt="Growing Me logo" class="h-10 w-10 rounded-full" />
				<span class="font-heading text-xl font-semibold text-gray-900 dark:text-gray-100"
					>Growing Me</span
				>
			</a>
		</div>

		<!-- Green divider -->
		<div class="mx-auto flex max-w-6xl px-6 my-4 h-[2px] bg-brand"></div>

		<!-- Nav links -->
		<div class="flex justify-center py-2">
			<nav>
				<ul class="flex items-center gap-4">
					<li>
						<a
							href="/"
							class="text-sm text-gray-600 transition-colors hover:text-brand dark:text-gray-400 dark:hover:text-sage-300"
							>Home</a
						>
					</li>
					<li>
						<a
							href="/about"
							class="text-sm text-gray-600 transition-colors hover:text-brand dark:text-gray-400 dark:hover:text-sage-300"
							>About</a
						>
					</li>
					<li>
						<a
							href="/articles"
							class="text-sm text-gray-600 transition-colors hover:text-brand dark:text-gray-400 dark:hover:text-sage-300"
							>Articles</a
						>
					</li>
					<li>
						<a
							href="/podcast"
							class="text-sm text-gray-600 transition-colors hover:text-brand dark:text-gray-400 dark:hover:text-sage-300"
							>Podcast</a
						>
					</li>
					<li>
						<a
							href="/contact"
							class="text-sm text-gray-600 transition-colors hover:text-brand dark:text-gray-400 dark:hover:text-sage-300"
							>Contact</a
						>
					</li>
				</ul>
			</nav>
		</div>

		<!-- Subscribe section -->
		<div class="flex justify-center pt-8">
			<EmailSubscribe />
		</div>

		<!-- Bottom: Social + Copyright -->
		<div
			class="mt-8 flex flex-col items-center gap-4 pt-4 dark:border-sage-700"
		>
			<SocialLinks size={18} />
			<p class="text-xs text-gray-500 dark:text-gray-500 py-3">
				&copy; {new Date().getFullYear()} Growing Me. All rights reserved.
			</p>
		</div>
	</div>
</footer>
