// src/lib/components/articles/FeaturedArticle.svelte
<script lang="ts">
	import type { PostMeta } from '$lib/utils/posts';
	import { formatDate } from '$lib/utils/format-date';
	import Button from '$lib/components/shared/Button.svelte';

	let { post }: { post: PostMeta } = $props();
</script>

<div class="grid gap-8 md:grid-cols-2 md:items-center">
	<!-- Image -->
	<div class="aspect-[4/3] overflow-hidden rounded-xl bg-sage-100 dark:bg-sage-800">
		{#if post.image}
			<img
				src={post.image}
				alt={post.title}
				class="h-full w-full object-cover transition-transform duration-300 hover:scale-105"
			/>
		{:else}
			<div class="flex h-full w-full items-center justify-center text-sage-400">Featured</div>
		{/if}
	</div>

	<!-- Content -->
	<div>
		{#if post.category}
			<span
				class="inline-block rounded-full bg-sage-100 px-3 py-1 text-xs font-medium text-sage-700 dark:bg-sage-800 dark:text-sage-300"
			>
				{post.category}
			</span>
		{/if}
		<h2 class="mt-3 font-heading text-2xl font-bold text-gray-900 md:text-3xl dark:text-gray-100">
			{post.title}
		</h2>
		<p class="mt-3 text-sm text-gray-500 dark:text-gray-500">
			{post.author} &bull; {formatDate(post.date)}
		</p>
		<div class="mt-6">
			<Button href="/articles/{post.slug}" variant="secondary">Read Full Article</Button>
		</div>
	</div>
</div>

// web/src/lib/components/FeaturedArticle.tsx
import Link from 'next/link'

interface FeaturedArticleProps {
  article: {
    title: string;
    image?: string;
    author: string;
    date: string;
    chapters?: { header: string }[];
  }
}

export default function FeaturedArticle({ article }: FeaturedArticleProps) {
    if (!article) return null

    return (
        <div className="grid md:grid-cols-2 gap-8 items-center">
            {article.image && (
                <div className="aspect-video overflow-hidden rounded-lg">
                    <img 
                        src={article.image} 
                        alt={article.title} 
                        className="w-full h-full object-cover hover:scale-105 transition-transform"
                    />
                </div>
            )}

            <div>
                <h1 className="text-3xl font-bold mb-4">{article.title}</h1>
                
                <div className="flex items-center text-gray-600 mb-4">
                    <span>{article.author}</span>
                    <span className="mx-2">•</span>
                    <time>{new Date(article.date).toLocaleDateString()}</time>
                </div>

                {article.chapters && article.chapters.length > 0 && (
                    <p className="text-lg mb-6">{article.chapters[0].header}</p>
                )}

                <Link 
                    href={`/articles/${encodeURIComponent(article.title)}`} 
                    className="inline-block bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition-colors"
                >
                    Read Full Article
                </Link>
            </div>
        </div>
    )
}
